export const uiCopy = {
  en: {
    skip: 'Skip to main content', name: 'Licence Path', language: 'हिंदी में देखें',
    disclosure: 'Independent concept prototype — not an official government service. No application, payment or appointment is submitted.',
    back: 'Back', continue: 'Continue', saveExit: 'Save and exit', preview: 'Preview stage',
    homeEyebrow: 'One clear journey', homeTitle: 'Prepare for your licence application with confidence.',
    homeBody: 'Understand every stage, prepare what you need, and return without losing your place. Official actions still happen on Sarathi.',
    start: 'Start a demo application', continueApplication: 'Continue saved application', existingStart: 'I already have a licence',
    featureJourney: 'See the whole journey', featureJourneyText: 'Know what comes next before you begin.',
    featureSave: 'Return without losing your place', featureSaveText: 'This demo saves fictional progress on this device.',
    featureSafe: 'No real personal data', featureSafeText: 'Use only the fictional applicant provided.',
    applicantQuestion: 'Are you applying for a driving licence for the first time?',
    firstTime: 'Yes, this is my first application', existing: 'No, I already have a licence',
    profileEyebrow: 'Fictional demo profile', profileTitle: 'Meet Maya Sen.',
    profileBody: 'Use this fictional profile to explore save and resume safely. Do not enter your own information.',
    profileBadge: 'Demo applicant — no real identity', useProfile: 'Continue as Maya',
    profilePrivacy: 'No account is created. Fictional progress is stored only in this browser.',
    welcome: 'Welcome back, Maya.', savedOnDevice: 'Demo progress saved on this device',
    progressSaved: 'Fictional progress saved in this browser only',
    savedExitConfirmation: 'Progress saved in this browser. You can continue from the next incomplete step when you return.',
    lastSaved: 'Last saved', nextAction: 'Next best action', openPassport: 'View Journey Passport', clear: 'Clear demo progress',
    clearConfirm: 'Clear all fictional progress and start again?', preparedScenario: 'Load prepared test scenario',
    passportEyebrow: 'My Licence Path', passportTitle: 'Your Journey Passport',
    passportBody: 'Preview every stage. We will unlock the next action when its prerequisites are ready.',
    statuses: { pending: 'Pending', 'needs-attention': 'Needs attention', completed: 'This step is completed', 'official-pending': 'Official step — pending' },
    stageHelp: { pending: 'This step has not been completed yet.', 'needs-attention': 'Resolve the highlighted requirement first.', completed: 'Completed in this prototype. No government action was completed.', 'official-pending': 'Use the illustrative action to explore this official step. Nothing happens on Sarathi.' },
    routeTitle: 'Find the route that applies.', routeBody: 'These choices change the requirements we show. Nothing is submitted.',
    state: 'State where the fictional applicant will apply', category: 'Applicant category',
    categoryHint: 'This is an official status category—not caste or reservation category.', identityRoute: 'How would the applicant continue?',
    aadhaar: 'Use Aadhaar eKYC on the official service', aadhaarHelp: 'May reduce uploads or RTO visits where the state enables it. Requires official authentication and an Aadhaar-linked mobile.',
    nonAadhaar: 'Continue without Aadhaar', nonAadhaarHelp: 'Photo and signature are required, and West Bengal requires an RTO visit for document verification.',
    ageBand: 'Applicant age group', adult: '18–39 years', older: '40 years or above',
    vehicle: 'Vehicle the applicant wants to learn', two: 'Motorcycle with gear (MCWG)', car: 'Car / Light Motor Vehicle (LMV)',
    specialTitle: 'This category needs specialist official guidance.', specialBody: 'The demo will not guess legal-presence, medical, diplomatic or supporting-document requirements. Review the official service for the current route.',
    officialHandoff: 'Open official Sarathi service', completeRoute: 'Complete route',
    applicationTitle: 'Review the fictional application.', applicationBody: 'Correct what does not match Maya’s intended LMV application.',
    fictionalApplicant: 'Fictional applicant', intendedVehicle: 'Intended vehicle', applicationVehicle: 'Vehicle currently on application', completeApplication: 'Complete application details',
    mismatch: 'This does not match the intended vehicle. Change it before continuing.', rto: 'Illustrative RTO context',
    rtoOption: 'Choose an example RTO', formOne: 'I reviewed the illustrative Form 1 fitness-declaration reminder.',
    formOneHelp: 'The real declaration and any medical evidence must be completed on the official service.',
    documentsTitle: 'Prepare document choices.', documentsBody: 'Choose example document types only. No file is uploaded or verified.',
    identityProof: 'Example identity/age proof', addressProof: 'Example address proof', chooseProof: 'Choose an example proof',
    passport: 'Passport', electoral: 'Electoral roll / voter document', school: 'School certificate', otherOfficial: 'Another officially accepted proof',
    missingProof: 'Choose an example address proof to resolve this stage.', rtoVisit: 'I understand the non-Aadhaar route requires an RTO visit for official document verification.',
    docsReady: 'Mark document preparation ready',
    photoTitle: 'Photo and signature', photoBody: 'The non-Aadhaar route requires both on the official service.', photoAadhaarBody: 'For this Aadhaar eKYC example, only the signature remains to be uploaded on the official service. Confirm current state availability there.',
    paymentTitle: 'Fee payment', paymentBody: 'Sarathi calculates the current fee and processes the real payment.',
    verifyTitle: 'Verify payment', verifyBody: 'Payment status is checked separately. A pending status may require another check before continuing.',
    receiptTitle: 'Receipt', receiptBody: 'The official receipt is available only after successful payment verification.',
    rtoReminder: 'Official dependency: Maya must visit the selected RTO with required originals for document verification.',
    mockBoundaries: {
      photo: 'Demo only — this control does not upload a photo or signature.',
      payment: 'Demo only — this control does not charge money or collect payment data.',
      verification: 'Demo only — this control does not check a real payment status.',
      receipt: 'Demo only — this control does not create an official receipt or reference.',
    },
    demoActionTitle: 'What this demo records',
    mockDescriptions: {
      photo: 'Record that Maya has understood the photo-and-signature upload checkpoint, then continue to fee payment.',
      payment: 'Record an illustrative payment checkpoint without entering an amount, card, bank or transaction detail.',
      verification: 'Record that the separate payment-status check has been understood. No government record is queried.',
      receipt: 'Record the receipt dependency without generating a downloadable or official-looking receipt.',
    },
    mockActions: { photo: 'Simulate upload completion', payment: 'Simulate fee payment', verification: 'Simulate payment-status check', receipt: 'Simulate receipt checkpoint' },
    mockCompletedByStage: {
      photo: 'Upload checkpoint recorded in this prototype. No photo or signature was uploaded; the real upload is still required on Sarathi.',
      payment: 'Payment checkpoint recorded in this prototype. No money was charged; the real payment is still required on Sarathi.',
      verification: 'Verification checkpoint recorded in this prototype. No government payment status was checked.',
      receipt: 'Receipt checkpoint recorded in this prototype. No official receipt or reference was created.',
    },
    previousMockComplete: 'completed in this prototype; the real action remains on Sarathi.',
    continueToStages: { payment: 'Continue to fee payment', verification: 'Continue to payment verification', receipt: 'Continue to receipt' },
    checkpointContinue: 'Continue to illustrative slot',
    slotTitle: 'Choose an illustrative test slot.', slotBody: 'Dates and times are mock availability. Nothing will be booked.',
    dateLabel: 'Choose any future date', timeLabel: 'Choose an illustrative time', morning: 'Morning · 10:30 AM', afternoon: 'Afternoon · 2:30 PM',
    noTimes: 'No times work for me', noTimesTitle: 'Try a different illustrative date.', noTimesBody: 'Change the date above. Real availability must be checked on Sarathi.',
    reviewTitle: 'Review the illustrative slot', confirmSlot: 'Confirm illustrative slot',
    confirmationEyebrow: 'Prepared in prototype', confirmationTitle: 'Maya’s next action is clear.',
    confirmationBody: 'No application, payment or appointment exists. Use the official service for every real action.',
    selectedDate: 'Illustrative date and time', routeSummary: 'Prepared route', rtoSummary: 'RTO verification',
    nextOfficial: 'What happens next on the official journey', nextSteps: ['Complete the official application, uploads, fee, verification and receipt.', 'Visit the RTO for non-Aadhaar document verification as instructed.', 'Attend the tutorial/test, then follow the official result and licence-printing instructions.'],
    returnProfile: 'Return to demo profile',
    existingTitle: 'What do you need to do today?', existingBody: 'Choose the service closest to your existing-licence need.',
    existingGuidance: 'Use the official service to confirm current state-specific requirements. This companion does not collect your licence details.',
  },
  hi: {
    skip: 'मुख्य सामग्री पर जाएँ', name: 'लाइसेंस पथ', language: 'View in English',
    disclosure: 'स्वतंत्र अवधारणा प्रोटोटाइप — यह सरकारी सेवा नहीं है। कोई आवेदन, भुगतान या अपॉइंटमेंट जमा नहीं होता।',
    back: 'वापस', continue: 'आगे बढ़ें', saveExit: 'सहेजें और बाहर जाएँ', preview: 'चरण देखें',
    homeEyebrow: 'एक स्पष्ट यात्रा', homeTitle: 'विश्वास के साथ लाइसेंस आवेदन की तैयारी करें।',
    homeBody: 'हर चरण समझें, ज़रूरी चीज़ें तैयार करें और अपनी जगह खोए बिना वापस आएँ। आधिकारिक कार्य सारथी पर ही होंगे।',
    start: 'डेमो आवेदन शुरू करें', continueApplication: 'सहेजा आवेदन जारी रखें', existingStart: 'मेरे पास पहले से लाइसेंस है',
    featureJourney: 'पूरी यात्रा देखें', featureJourneyText: 'शुरू करने से पहले जानें कि आगे क्या होगा।',
    featureSave: 'अपनी जगह खोए बिना लौटें', featureSaveText: 'यह डेमो काल्पनिक प्रगति इसी डिवाइस पर सहेजता है।',
    featureSafe: 'कोई वास्तविक निजी डेटा नहीं', featureSafeText: 'केवल दिए गए काल्पनिक आवेदक का उपयोग करें।',
    applicantQuestion: 'क्या आप पहली बार ड्राइविंग लाइसेंस के लिए आवेदन कर रहे हैं?',
    firstTime: 'हाँ, यह मेरा पहला आवेदन है', existing: 'नहीं, मेरे पास पहले से लाइसेंस है',
    profileEyebrow: 'काल्पनिक डेमो प्रोफ़ाइल', profileTitle: 'माया सेन से मिलें।',
    profileBody: 'सहेजने और दोबारा शुरू करने का अनुभव सुरक्षित रूप से देखने के लिए इस काल्पनिक प्रोफ़ाइल का उपयोग करें। अपनी जानकारी दर्ज न करें।',
    profileBadge: 'डेमो आवेदक — कोई वास्तविक पहचान नहीं', useProfile: 'माया के रूप में आगे बढ़ें',
    profilePrivacy: 'कोई खाता नहीं बनता। काल्पनिक प्रगति केवल इस ब्राउज़र में सहेजी जाती है।',
    welcome: 'वापसी पर स्वागत है, माया।', savedOnDevice: 'डेमो प्रगति इस डिवाइस पर सहेजी गई',
    progressSaved: 'काल्पनिक प्रगति केवल इस ब्राउज़र में सहेजी गई',
    savedExitConfirmation: 'प्रगति इस ब्राउज़र में सहेजी गई। लौटने पर आप अगले अधूरे चरण से जारी रख सकते हैं।',
    lastSaved: 'अंतिम बार सहेजा', nextAction: 'अगला सबसे अच्छा कार्य', openPassport: 'जर्नी पासपोर्ट देखें', clear: 'डेमो प्रगति मिटाएँ',
    clearConfirm: 'सारी काल्पनिक प्रगति मिटाकर फिर से शुरू करें?', preparedScenario: 'तैयार टेस्ट स्थिति लोड करें',
    passportEyebrow: 'मेरा लाइसेंस पथ', passportTitle: 'आपका जर्नी पासपोर्ट',
    passportBody: 'हर चरण देखें। आवश्यक तैयारी पूरी होने पर अगला कार्य उपलब्ध होगा।',
    statuses: { pending: 'लंबित', 'needs-attention': 'ध्यान आवश्यक', completed: 'यह चरण पूरा है', 'official-pending': 'आधिकारिक चरण — लंबित' },
    stageHelp: { pending: 'यह चरण अभी पूरा नहीं हुआ है।', 'needs-attention': 'पहले बताई गई आवश्यकता पूरी करें।', completed: 'इस प्रोटोटाइप में पूरा हुआ। कोई सरकारी कार्य पूरा नहीं हुआ।', 'official-pending': 'इस आधिकारिक चरण को समझने के लिए उदाहरणात्मक कार्रवाई करें। सारथी पर कुछ नहीं होगा।' },
    routeTitle: 'अपने लिए सही मार्ग जानें।', routeBody: 'इन विकल्पों के अनुसार आवश्यकताएँ बदलेंगी। कुछ भी जमा नहीं होगा।',
    state: 'काल्पनिक आवेदक किस राज्य में आवेदन करेगा', category: 'आवेदक श्रेणी',
    categoryHint: 'यह आधिकारिक स्थिति श्रेणी है—जाति या आरक्षण श्रेणी नहीं।', identityRoute: 'आवेदक कैसे आगे बढ़ेगा?',
    aadhaar: 'आधिकारिक सेवा पर आधार eKYC का उपयोग करें', aadhaarHelp: 'राज्य में उपलब्ध होने पर अपलोड या RTO यात्रा कम हो सकती है। आधिकारिक प्रमाणीकरण और आधार से जुड़ा मोबाइल आवश्यक है।',
    nonAadhaar: 'आधार के बिना आगे बढ़ें', nonAadhaarHelp: 'फोटो और हस्ताक्षर आवश्यक हैं, और पश्चिम बंगाल में दस्तावेज़ सत्यापन के लिए RTO जाना होगा।',
    ageBand: 'आवेदक आयु समूह', adult: '18–39 वर्ष', older: '40 वर्ष या अधिक',
    vehicle: 'आवेदक कौन सा वाहन सीखना चाहता है', two: 'गियर वाली मोटरसाइकिल (MCWG)', car: 'कार / हल्का मोटर वाहन (LMV)',
    specialTitle: 'इस श्रेणी को विशेषज्ञ आधिकारिक मार्गदर्शन चाहिए।', specialBody: 'डेमो कानूनी निवास, चिकित्सा, राजनयिक या सहायक दस्तावेज़ आवश्यकताओं का अनुमान नहीं लगाएगा। वर्तमान मार्ग के लिए आधिकारिक सेवा देखें।',
    officialHandoff: 'आधिकारिक सारथी सेवा खोलें', completeRoute: 'मार्ग पूरा करें',
    applicationTitle: 'काल्पनिक आवेदन की समीक्षा करें।', applicationBody: 'माया के LMV आवेदन से मेल न खाने वाली जानकारी ठीक करें।',
    fictionalApplicant: 'काल्पनिक आवेदक', intendedVehicle: 'इच्छित वाहन', applicationVehicle: 'आवेदन में वर्तमान वाहन', completeApplication: 'आवेदन विवरण पूरा करें',
    mismatch: 'यह इच्छित वाहन से मेल नहीं खाता। आगे बढ़ने से पहले इसे बदलें।', rto: 'उदाहरण RTO संदर्भ',
    rtoOption: 'उदाहरण RTO चुनें', formOne: 'मैंने उदाहरणात्मक Form 1 फिटनेस घोषणा अनुस्मारक देखा है।',
    formOneHelp: 'वास्तविक घोषणा और चिकित्सा प्रमाण आधिकारिक सेवा पर पूरा करना होगा।',
    documentsTitle: 'दस्तावेज़ विकल्प तैयार करें।', documentsBody: 'केवल उदाहरण दस्तावेज़ प्रकार चुनें। कोई फ़ाइल अपलोड या सत्यापित नहीं होती।',
    identityProof: 'उदाहरण पहचान/आयु प्रमाण', addressProof: 'उदाहरण पता प्रमाण', chooseProof: 'उदाहरण प्रमाण चुनें',
    passport: 'पासपोर्ट', electoral: 'मतदाता सूची / मतदाता दस्तावेज़', school: 'स्कूल प्रमाणपत्र', otherOfficial: 'कोई अन्य आधिकारिक रूप से स्वीकृत प्रमाण',
    missingProof: 'इस चरण को पूरा करने के लिए उदाहरण पता प्रमाण चुनें।', rtoVisit: 'मैं समझता/समझती हूँ कि गैर-आधार मार्ग में आधिकारिक दस्तावेज़ सत्यापन के लिए RTO जाना होगा।',
    docsReady: 'दस्तावेज़ तैयारी तैयार चिह्नित करें',
    photoTitle: 'फोटो और हस्ताक्षर', photoBody: 'गैर-आधार मार्ग में दोनों आधिकारिक सेवा पर आवश्यक हैं।', photoAadhaarBody: 'इस आधार eKYC उदाहरण में आधिकारिक सेवा पर केवल हस्ताक्षर अपलोड करना बाकी है। राज्य में वर्तमान उपलब्धता वहीं जाँचें।',
    paymentTitle: 'शुल्क भुगतान', paymentBody: 'सारथी वर्तमान शुल्क की गणना और वास्तविक भुगतान करता है।',
    verifyTitle: 'भुगतान सत्यापित करें', verifyBody: 'भुगतान स्थिति अलग से जाँची जाती है। लंबित स्थिति में आगे बढ़ने से पहले फिर जाँच करनी पड़ सकती है।',
    receiptTitle: 'रसीद', receiptBody: 'आधिकारिक रसीद सफल भुगतान सत्यापन के बाद ही उपलब्ध होती है।',
    rtoReminder: 'आधिकारिक आवश्यकता: माया को दस्तावेज़ सत्यापन के लिए आवश्यक मूल दस्तावेज़ों के साथ चुने गए RTO जाना होगा।',
    mockBoundaries: {
      photo: 'केवल डेमो — यह नियंत्रण फोटो या हस्ताक्षर अपलोड नहीं करता।',
      payment: 'केवल डेमो — यह नियंत्रण पैसे नहीं काटता और भुगतान जानकारी नहीं लेता।',
      verification: 'केवल डेमो — यह नियंत्रण वास्तविक भुगतान स्थिति नहीं जाँचता।',
      receipt: 'केवल डेमो — यह नियंत्रण आधिकारिक रसीद या संदर्भ नहीं बनाता।',
    },
    demoActionTitle: 'यह डेमो क्या दर्ज करता है',
    mockDescriptions: {
      photo: 'दर्ज करें कि माया ने फोटो और हस्ताक्षर अपलोड चेकपॉइंट समझ लिया है, फिर शुल्क भुगतान पर जाएँ।',
      payment: 'राशि, कार्ड, बैंक या लेन-देन विवरण डाले बिना एक उदाहरणात्मक भुगतान चेकपॉइंट दर्ज करें।',
      verification: 'दर्ज करें कि अलग भुगतान-स्थिति जाँच समझ ली गई है। किसी सरकारी रिकॉर्ड की जाँच नहीं होती।',
      receipt: 'डाउनलोड करने योग्य या आधिकारिक दिखने वाली रसीद बनाए बिना रसीद की आवश्यकता दर्ज करें।',
    },
    mockActions: { photo: 'अपलोड पूरा होने का डेमो देखें', payment: 'शुल्क भुगतान का डेमो देखें', verification: 'भुगतान स्थिति जाँच का डेमो देखें', receipt: 'रसीद चरण का डेमो देखें' },
    mockCompletedByStage: {
      photo: 'इस प्रोटोटाइप में अपलोड चेकपॉइंट दर्ज हुआ। कोई फोटो या हस्ताक्षर अपलोड नहीं हुआ; वास्तविक अपलोड अभी भी सारथी पर करना होगा।',
      payment: 'इस प्रोटोटाइप में भुगतान चेकपॉइंट दर्ज हुआ। कोई पैसा नहीं कटा; वास्तविक भुगतान अभी भी सारथी पर करना होगा।',
      verification: 'इस प्रोटोटाइप में सत्यापन चेकपॉइंट दर्ज हुआ। किसी सरकारी भुगतान स्थिति की जाँच नहीं हुई।',
      receipt: 'इस प्रोटोटाइप में रसीद चेकपॉइंट दर्ज हुआ। कोई आधिकारिक रसीद या संदर्भ नहीं बना।',
    },
    previousMockComplete: 'इस प्रोटोटाइप में पूरा हुआ; वास्तविक कार्य सारथी पर बाकी है।',
    continueToStages: { payment: 'शुल्क भुगतान पर जाएँ', verification: 'भुगतान सत्यापन पर जाएँ', receipt: 'रसीद पर जाएँ' },
    checkpointContinue: 'उदाहरणात्मक स्लॉट पर जाएँ',
    slotTitle: 'उदाहरणात्मक टेस्ट स्लॉट चुनें।', slotBody: 'तारीख और समय मॉक उपलब्धता हैं। कुछ भी बुक नहीं होगा।',
    dateLabel: 'कोई भी भविष्य की तारीख चुनें', timeLabel: 'उदाहरणात्मक समय चुनें', morning: 'सुबह · 10:30 AM', afternoon: 'दोपहर · 2:30 PM',
    noTimes: 'कोई समय मेरे लिए सही नहीं', noTimesTitle: 'दूसरी उदाहरणात्मक तारीख चुनें।', noTimesBody: 'ऊपर तारीख बदलें। वास्तविक उपलब्धता सारथी पर जाँचनी होगी।',
    reviewTitle: 'उदाहरणात्मक स्लॉट की समीक्षा करें', confirmSlot: 'उदाहरणात्मक स्लॉट की पुष्टि करें',
    confirmationEyebrow: 'प्रोटोटाइप में तैयार', confirmationTitle: 'माया का अगला कार्य स्पष्ट है।',
    confirmationBody: 'कोई आवेदन, भुगतान या अपॉइंटमेंट मौजूद नहीं है। हर वास्तविक कार्य के लिए आधिकारिक सेवा का उपयोग करें।',
    selectedDate: 'उदाहरणात्मक तारीख और समय', routeSummary: 'तैयार मार्ग', rtoSummary: 'RTO सत्यापन',
    nextOfficial: 'आधिकारिक यात्रा में आगे क्या होगा', nextSteps: ['आधिकारिक आवेदन, अपलोड, शुल्क, सत्यापन और रसीद पूरी करें।', 'निर्देशानुसार गैर-आधार दस्तावेज़ सत्यापन के लिए RTO जाएँ।', 'ट्यूटोरियल/टेस्ट में शामिल हों, फिर आधिकारिक परिणाम और लाइसेंस प्रिंट निर्देशों का पालन करें।'],
    returnProfile: 'डेमो प्रोफ़ाइल पर लौटें',
    existingTitle: 'आज आपको क्या करना है?', existingBody: 'अपने मौजूदा लाइसेंस की ज़रूरत के सबसे निकट सेवा चुनें।',
    existingGuidance: 'राज्य की वर्तमान आवश्यकताओं के लिए आधिकारिक सेवा देखें। यह साथी आपके लाइसेंस की जानकारी नहीं लेता।',
  },
}

export const journeyStages = {
  en: [
    ['route', 'Find my route'], ['application', 'Application details'], ['documents', 'Documents'], ['photo', 'Photo and signature'],
    ['payment', 'Fee payment'], ['verification', 'Verify payment'], ['receipt', 'Receipt'], ['slot', 'Test slot'],
  ],
  hi: [
    ['route', 'अपना मार्ग जानें'], ['application', 'आवेदन विवरण'], ['documents', 'दस्तावेज़'], ['photo', 'फोटो और हस्ताक्षर'],
    ['payment', 'शुल्क भुगतान'], ['verification', 'भुगतान सत्यापन'], ['receipt', 'रसीद'], ['slot', 'टेस्ट स्लॉट'],
  ],
}

export const categories = [
  ['diplomat', 'Diplomats (Foreigner)', 'राजनयिक (विदेशी)'],
  ['foreigner', 'Foreigners (But not Diplomats)', 'विदेशी (राजनयिक नहीं)'],
  ['general', 'General', 'सामान्य'],
  ['oci', 'OCI', 'OCI'],
  ['divyang', 'Divyang (Differently Abled)', 'दिव्यांग'],
  ['repatriate', 'Repatriate', 'स्वदेश लौटे व्यक्ति'],
  ['refugee', 'Refugees', 'शरणार्थी'],
  ['ex-service', 'Ex-Servicemen', 'भूतपूर्व सैनिक'],
].map(([value, en, hi]) => ({ value, label: { en, hi } }))

export const existingServices = [
  ['renew', 'Renew my driving licence', 'ड्राइविंग लाइसेंस नवीनीकृत करें'],
  ['details', 'Update my address or details', 'पता या जानकारी अपडेट करें'],
  ['duplicate', 'Replace a lost or damaged licence', 'खोया या खराब लाइसेंस बदलें'],
  ['status', 'Check application or delivery status', 'आवेदन या डिलीवरी स्थिति जाँचें'],
].map(([value, en, hi]) => ({ value, label: { en, hi } }))

export const rtos = [
  ['kolkata', 'Kolkata (illustrative)', 'कोलकाता (उदाहरण)'],
  ['howrah', 'Howrah (illustrative)', 'हावड़ा (उदाहरण)'],
  ['north24', 'North 24 Parganas (illustrative)', 'उत्तर 24 परगना (उदाहरण)'],
].map(([value, en, hi]) => ({ value, label: { en, hi } }))
